services:
  app:
    # IMPORTANT: Replace this with your GitHub username and repository name
    # For example: image: ghcr.io/my-username/my-new-project:latest
    image: ghcr.io/lulf87/Document:latest
    ports:
      - "8004:8004"
    volumes:
      # This maps a local 'uploaded_files' directory to the container's data directory.
      # Users must create this directory locally before running the container.
      - ./uploaded_files:/app/backend/uploaded_files
    restart: unless-stopped
    pull_policy: always 