name: Docker Publish

# This workflow is triggered on pushes to the main branch
on:
  push:
    branches: [ "main" ]

env:
  # The name of the Docker image you want to build, e.g., ghcr.io/username/repo_name
  IMAGE_NAME: document

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Set permissions for the GITHUB_TOKEN for pushing to ghcr.io
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # The GITHUB_TOKEN is a special token that's automatically available in workflows.
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/document:latest
            ghcr.io/${{ github.repository_owner }}/document:${{ github.sha }} 